name: Codecov

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  codecov:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.17  # Change this to your Go version

      - name: Run tests and generate coverage
        run: |
          # Replace the following with your test command and coverage generation command
          go test -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out

      - name: Upload coverage to Codecov
        run: |
          bash <(curl -s https://codecov.io/bash)
